# Generated by Django 2.2.10 on 2020-09-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-master', 'scope'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
